# Use a specific version of the Python image
FROM python:3.9

# Set the working directory
WORKDIR /data

# Copy only the requirements.txt file
COPY requirements.txt .

# Upgrade pip and setuptools, install requirements, and clean up in one layer
RUN apt-get update --yes --no-install-recommends && \
    apt install git-all --yes --no-install-recommends && \
    pip install --upgrade pip setuptools && \
    pip install --no-cache-dir -r requirements.txt && \
    rm requirements.txt && \
    git config --global user.name "piotreks" && \
    git config --global user.email "" && \
    curl https://cli-assets.heroku.com/install-ubuntu.sh | sh && \
    heroku update
